config/routes.rb
Rails.application.routes.draw do

  get 'upload' => 'images#new', :as => 'upload'
  
  get 'images/new'

  get 'images/create'

  get 'images/destroy'

  get 'images/index'

  get 'categories/new'

  get 'categories/create'

  get 'categories/edit'

  get 'categories/update'

  get 'categories/destroy'

  get 'categories/show'

  resources :images, :categories

  root 'images#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :getCategoryNav
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def getCategoryNav
  	@categoryNav = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category Created"

      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
  @image = Image.new
  end


  def create
    @image = Image.new(image_params)

    if @image.save
      flash[:notice] = "Image Created"

      redirect_to root_path
    else
      render 'new'
    end
end
  def destroy
  end

  def index
  end

  private
  def image_params
    params.require(:image).permit(:image, :category_id, :image_title, :image_description, :image_file_size, :image_content_type, :remote_image_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= form_for @category do |f| %>
	<!-- check for errors -->
	<% if @category.errors.any? %>
	<% @category.errors.full_messages.each do |msg| %>
	<!-- show errors -->
	<div class="alert alert-danger"><%= msg %></div>
	<% end %>
<% end %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name ,class:'form-control' %>
	</div>
	<br>
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to 'Cancel', categories_path, class:'btn btn-default' %>
	<% end %>

app/views/categories/new.html.erb
<h2>Add New Category</h2>

<%= form_for @category do |f| %>
	<!-- check for errors -->
	<% if @category.errors.any? %>
	<% @category.errors.full_messages.each do |msg| %>
	<!-- show errors -->
	<div class="alert alert-danger"><%= msg %></div>
	<% end %>
	<% end %>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name ,class:'form-control' %>
	</div>
	<br>
	<%= f.submit "Submit", class: 'btn btn-primary' %>
	<%= link_to 'Cancel', categories_path, class:'btn btn-default' %>
	<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/destroy.html.erb
<h1>Images#destroy</h1>
<p>Find me in app/views/images/destroy.html.erb</p>

app/views/images/index.html.erb
  <div id="gallery">
      <h2> All Images</h2>
      <div class="row">
        <div class="col-md-3">
         <div class="photo photo-type-line">
         <a href="img/bt1.jpg" class="photo-hover" data-lightbox="my-images" data-title="Lorem Ipsum">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt1.jpg"></div>
    </div>
  </div>
         <div class="col-md-3">
         <div class="photo photo-type-line">
         <a href="img/bt2.jpg" class="photo-hover" data-lightbox="my-images" data-title="Lorem Ipsum">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt2.jpg"></div>
    </div>
  </div>
         <div class="col-md-3">
         <div class="photo photo-type-line">
         <a href="img/bt3.jpg" class="photo-hover" data-lightbox="my-images" data-title="Lorem Ipsum">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt3.jpg"></div>
    </div>
  </div>
       <div class="col-md-3">
         <div class="photo photo-type-line">
         <a href="img/bt4.jpg" class="photo-hover" data-lightbox="my-images" data-title="Lorem Ipsum">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt4.jpg"></div>
      </div>
     </div>
    </div>

     <div class="row">
        <div class="col-md-3">
         <div class="photo photo-type-line">
         <a href="img/bt5.jpg" class="photo-hover" data-lightbox="my-images" data-title="Lorem Ipsum">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt5.jpg"></div>
    </div>
  </div>
         <div class="col-md-3">
         <div class="photo photo-type-line">
         <a href="img/bt6.jpg" class="photo-hover" data-lightbox="my-images" data-title="Lorem Ipsum">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt6.jpg"></div>
    </div>
  </div>
         <div class="col-md-3">
         <div class="photo photo-type-line">
         <a href="img/bt7.jpg" class="photo-hover" data-lightbox="my-images" data-title="Lorem Ipsum">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt7.jpg"></div>
    </div>
  </div>
       <div class="col-md-3">
         <div class="photo photo-type-line">
         <a href="img/bt8.jpg" class="photo-hover" data-lightbox="my-images" data-title="Lorem Ipsum">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt8.jpg"></div>
      </div>
     </div>
    </div>

     <div class="row">
        <div class="col-md-3">
         <div class="photo photo-type-line">
         <a href="img/bt9.jpg" class="photo-hover" data-lightbox="my-images" data-title="Lorem Ipsum">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt9.jpg"></div>
    </div>
  </div>
         <div class="col-md-3">
         <div class="photo photo-type-line">
         <a href="img/bt10.jpg" class="photo-hover" data-lightbox="my-images" data-title="Lorem Ipsum">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt10.jpg"></div>
    </div>
  </div>
         <div class="col-md-3">
         <div class="photo photo-type-line">
         <a href="img/bt11.jpg" class="photo-hover" data-lightbox="my-images" data-title="Lorem Ipsum">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt11.jpg"></div>
    </div>
  </div>
       <div class="col-md-3">
         <div class="photo photo-type-line">
         <a href="img/bt12.jpg" class="photo-hover" data-lightbox="my-images" data-title="Lorem Ipsum">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt12.jpg"></div>
      </div>
     </div>
    </div>

     <div class="row">
        <div class="col-md-3">
         <div class="photo photo-type-line">
         <a href="img/bt13.jpg" class="photo-hover" data-lightbox="my-images" data-title="Lorem Ipsum">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt13.jpg"></div>
    </div>
  </div>
         <div class="col-md-3">
         <div class="photo photo-type-line">
         <a href="img/bt14.jpg" class="photo-hover" data-lightbox="my-images" data-title="Lorem Ipsum">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt14.jpg"></div>
    </div>
  </div>
         <div class="col-md-3">
         <div class="photo photo-type-line">
         <a href="img/bt15.jpg" class="photo-hover" data-lightbox="my-images" data-title="Lorem Ipsum">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt15.jpg"></div>
    </div>
  </div>
       <div class="col-md-3">
         <div class="photo photo-type-line" data-lightbox="my-images" data-title="Lorem Ipsum">
         <a href="img/bt16.jpg" class="photo-hover">
         <div class="photo-info">
         <div class="headline">Lorem Ipsum</div>
         <div class="line"></div>
         <div class="desc">Lorem dolor sit amet, consecterur adipiscing elit. sed faucibus faucibus ni ut lobortis</div>
        </div>
        <div class="mask"></div>
      </a>
      <div class="photo-img"><img src="img/bt16.jpg"></div>
      </div>
     </div>
    </div>
   </div>

app/views/images/new.html.erb
<h2>Upload Image</h2>

<%= form_for @image, :html =>{:multipart => true} do |f| %>
	<!-- check for errors -->
	<% if @image.errors.any? %>
	<% @image.errors.full_messages.each do |msg| %>
	<!-- show errors -->
	<div class="alert alert-danger"><%= msg %></div>
	<% end %>
<% end %>

<div class="form-group">
	<%= f.label :image_title %>
	<%= f.text_field :image_title ,class:'form -control' %>
</div>

<div class="form-group">
	<%= f.label :category %>
	<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]},{:include_blank => 'Select One'}, class:'form-control' %>
</div>

<div class="form-group">
	<%= f.label :image_description %>
	<%= f.text_area :image_description ,class:'form -control' %>
</div>

<div class="form-group">
	<%= f.label :image %>
	<%= f.file_field :image %>
</div>


<br>

<%= f.submit "Submit", class:'btn btn-primary' %>
<%=link_to "Cancel", images_path, class:'btn btn-default' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RGallery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



    <nav class="navbar navbar-inverse " role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">RailsCMS</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "home", root_path %></li>
            <% @categoryNav.each do |category| %>
            <li> <% link_to category.name, category_path(category.id) %></li>
            <% end %> 
          </ul>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "upload photo", upload_path %></li>
            <li><%= link_to "Add Category", new_category_path %></li>
        </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

<section>
    <div class="container">
<!-- alerts & messages -->
    	<% if flash[:notice] %>
    	<div class="alert alert-success"><%= flash[:notice] %></div>
    	<% end %>

    	<% if flash[:alert] %>
    	<div class="alert alert-danger"><%= flash[:alert] %></div>
    	<% end %>
    <%= yield %>
    </div><!-- /.container -->
   </section>

   <footer>
    <p>Copyright @copy; 2014, rGallery</P>
    </footer>
</body>
</html>